[dev]
  command = "npm run dev"
  publish = "/dist"
  # We need another port for the application because Vite occupies the 3000.
  port = 8080

[build]
  base = "vite-vanilla-netlify-javascript/"
  command = "npm run build"
  functions = "vite-vanilla-netlify-javascript/functions/" # netlify dev uses this directory to scaffold and serve your functions
  publish = "vite-vanilla-netlify-javascript/dist"

[functions]
  # We are goint to use ES modules so we need esbuild to transpile the code.
  node_bundler = "esbuild"
  # This line will include into the environment a file with the mock data.
  # included_files = ["data/*.json"]

# We have to tell the Netlify that this URL will be served by the books.js function.
[[redirects]]
  from = "/api/ably/token"
  to = "/.netlify/functions/ably-token"
  status = 200